### ISSUE TITLE
cant connect db

### ISSUE THREAD

**Issue by User052216** [dr5hn/Simple-CRUD#4]
![image](https://user-images.githubusercontent.com/35529611/43084344-14651352-8ecb-11e8-92fc-7eb3929e4808.png)

**Comment by dr5hn** [comment]
@User052216 

Update Project Configuration Files as per your DB and Server Settings

- api/config/core.php
Update following variables as per your server config
$home_url = "http://localhost/Simple-CRUD/";

- api/config/database.php
Update following variables as per your database config
$host = "localhost";
private $db_name = "api_db";
private $username = "root";
private $password = "mysql"; // If you're using xampp keep it blank

Hence marking this issue as Closed
